include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'


# CUDA.jl

.test_cuda:
  extends: .test
  script:
    - julia -e 'using Pkg;
                Pkg.develop(PackageSpec(path=pwd()));
                Pkg.build();'
    - julia -e 'using Pkg;
                Pkg.add(PackageSpec(name="CUDA", rev="master"));
                Pkg.test("CUDA");'

cuda:1.5:
  extends:
    - .julia:1.5
    - .test_cuda
  tags:
    - nvidia
  allow_failure: true
